{"name": "test_login_1_failed_by_fail_datas", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('data', <FixtureRequest for <Function test_login_1_failed_by_fail_datas>>)", "trace": "file F:\\MyProject\\web_ketangpai\\TestCases\\test_login.py, line 42\n       @data(*ld.fail_datas)\n       def test_login_1_failed_by_fail_datas(self, data):\nE       fixture 'data' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, login_web, metadata, monkeypatch, open_url, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, refresh_page, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nF:\\MyProject\\web_ketangpai\\TestCases\\test_login.py:42"}, "start": 1562164538624, "stop": 1562164538624, "uuid": "4475dcff-9a42-44b6-bbb7-e4443948c683", "historyId": "1089353f49f9a778d150c7365897a4ef", "fullName": "TestCases.test_login.TestLogin#test_login_1_failed_by_fail_datas", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-F99FSHQ"}, {"name": "thread", "value": "5524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}