{"name": "test_login_2_success_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestLogin' object has no attribute 'driver'", "trace": "self = <TestCases.test_login.TestLogin object at 0x0000015C14DC0550>\n\n    def test_login_2_success_login(self):\n        # 步骤 - 登陆操作 - 登陆页面 - 18684720553、python\n>       LoginPage(self.driver).login(ld.success_data[\"user\"], ld.success_data[\"passwd\"])  # 测试对象+测试数据\nE       AttributeError: 'TestLogin' object has no attribute 'driver'\n\nTestCases\\test_login.py:28: AttributeError"}, "start": 1562162980866, "stop": 1562162980866, "uuid": "53507989-39c0-40a8-9b93-c96ce7d25cb0", "historyId": "70890bea4db005493b2ff2b6079d770f", "fullName": "TestCases.test_login.TestLogin#test_login_2_success_login", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-F99FSHQ"}, {"name": "thread", "value": "8984-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}