{
  "uid" : "75281e88ad980609",
  "name" : "test_login_0_failed_by_wrong_datas",
  "fullName" : "TestCases.test_login.TestLogin#test_login_0_failed_by_wrong_datas",
  "historyId" : "38a63bdc359a219cdbe9846dfc5cf26b",
  "time" : {
    "start" : 1562162980931,
    "stop" : 1562162980931,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "_pytest.fixtures.FixtureLookupError: ('data', <FixtureRequest for <Function test_login_0_failed_by_wrong_datas>>)",
  "statusTrace" : "file F:\\MyProject\\web_ketangpai\\TestCases\\test_login.py, line 35\n       @data(*ld.wrong_datas)\n       def test_login_0_failed_by_wrong_datas(self, data):\nE       fixture 'data' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, login_web, metadata, monkeypatch, open_url, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, refresh_page, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nF:\\MyProject\\web_ketangpai\\TestCases\\test_login.py:35",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "TestCases"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "DESKTOP-F99FSHQ"
  }, {
    "name" : "thread",
    "value" : "8984-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "TestCases.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "75281e88ad980609.json",
  "parameterValues" : [ ]
}